settings: #Please only change the String in the '. If you remove the '' then the System dont load.
          #More help at the Support link who stand still in the Console.
  cfgver: 0 #to reset the Config change the Number to any other Number that is higher when this!
  version: 'DEVELOPMENT'
  debug: false #If true, you see messages that you would not otherwise see.
  language: 'english'

message:
  prefix: '&8[&eLobby&8] &7'